/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/chart/chart.module';
import * as import2 from '@angular/common';
class ChartModuleInjector extends import0.ɵNgModuleInjector<import1.ChartModule> {
  _CommonModule_0:import2.CommonModule;
  _ChartModule_1:import1.ChartModule;
  __NgLocalization_2:import2.NgLocaleLocalization;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_2():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_2 == null)) { (this.__NgLocalization_2 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_2;
  }
  createInternal():import1.ChartModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ChartModule_1 = new import1.ChartModule();
    return this._ChartModule_1;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import1.ChartModule)) { return this._ChartModule_1; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_2; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ChartModuleNgFactory:import0.NgModuleFactory<import1.ChartModule> = new import0.NgModuleFactory<any>(ChartModuleInjector,import1.ChartModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvZWoyLWNoYXJ0LWNvbXBvbmVudHNfbWFzdGVyLVZTMk1UTUEzQU9FUUxJRUdJWUNUM1BVQlpFRENKRk9RSDNVVlZWRVhPV0dUSFVNR0E1TEEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2hhcnQvY2hhcnQubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlL2VqMi1jaGFydC1jb21wb25lbnRzX21hc3Rlci1WUzJNVE1BM0FPRVFMSUVHSVlDVDNQVUJaRURDSkZPUUgzVVZWVkVYT1dHVEhVTUdBNUxBL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NoYXJ0L2NoYXJ0Lm1vZHVsZS50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OyJ9
