/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/chart/chart-all.module';
import * as import2 from '@angular/common';
import * as import3 from '../../../src/chart/chart.module';
import * as import4 from '@syncfusion/ej2-charts/src/chart/series/line-series';
import * as import5 from '@syncfusion/ej2-charts/src/chart/series/scatter-series';
import * as import6 from '@syncfusion/ej2-charts/src/chart/series/column-series';
import * as import7 from '@syncfusion/ej2-charts/src/chart/series/spline-series';
import * as import8 from '@syncfusion/ej2-charts/src/chart/series/area-series';
import * as import9 from '@syncfusion/ej2-charts/src/chart/series/step-line-series';
import * as import10 from '@syncfusion/ej2-charts/src/chart/series/stacking-column-series';
import * as import11 from '@syncfusion/ej2-charts/src/chart/series/stacking-area-series';
import * as import12 from '@syncfusion/ej2-charts/src/chart/series/bar-series';
import * as import13 from '@syncfusion/ej2-charts/src/chart/series/stacking-bar-series';
import * as import14 from '@syncfusion/ej2-charts/src/chart/user-interaction/tooltip';
import * as import15 from '@syncfusion/ej2-charts/src/chart/user-interaction/crosshair';
import * as import16 from '@syncfusion/ej2-charts/src/chart/axis/category-axis';
import * as import17 from '@syncfusion/ej2-charts/src/chart/axis/date-time-axis';
import * as import18 from '@syncfusion/ej2-charts/src/chart/axis/logarithmic-axis';
import * as import19 from '@syncfusion/ej2-charts/src/chart/series/marker';
import * as import20 from '@syncfusion/ej2-charts/src/chart/legend/legend';
import * as import21 from '@syncfusion/ej2-charts/src/chart/user-interaction/zooming';
import * as import22 from '@syncfusion/ej2-charts/src/chart/series/data-label';
import * as import23 from '@syncfusion/ej2-charts/src/chart/user-interaction/selection';
class ChartAllModuleInjector extends import0.ɵNgModuleInjector<import1.ChartAllModule> {
  _CommonModule_0:import2.CommonModule;
  _ChartModule_1:import3.ChartModule;
  _ChartAllModule_2:import1.ChartAllModule;
  __NgLocalization_3:import2.NgLocaleLocalization;
  _LineSeries_4:any;
  _ScatterSeries_5:any;
  _ColumnSeries_6:any;
  _SplineSeries_7:any;
  _AreaSeries_8:any;
  _StepLineSeries_9:any;
  _StackingColumnSeries_10:any;
  _StackingAreaSeries_11:any;
  _BarSeries_12:any;
  _StackingBarSeries_13:any;
  _Tooltip_14:any;
  _Crosshair_15:any;
  _Category_16:any;
  _DateTime_17:any;
  _Logarithmic_18:any;
  _Marker_19:any;
  _Legend_20:any;
  _Zoom_21:any;
  _DataLabel_22:any;
  _Selection_23:any;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  get _NgLocalization_3():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_3 == null)) { (this.__NgLocalization_3 = new import2.NgLocaleLocalization(this.parent.get(import0.LOCALE_ID))); }
    return this.__NgLocalization_3;
  }
  createInternal():import1.ChartAllModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ChartModule_1 = new import3.ChartModule();
    this._ChartAllModule_2 = new import1.ChartAllModule();
    this._LineSeries_4 = import4.LineSeries;
    this._ScatterSeries_5 = import5.ScatterSeries;
    this._ColumnSeries_6 = import6.ColumnSeries;
    this._SplineSeries_7 = import7.SplineSeries;
    this._AreaSeries_8 = import8.AreaSeries;
    this._StepLineSeries_9 = import9.StepLineSeries;
    this._StackingColumnSeries_10 = import10.StackingColumnSeries;
    this._StackingAreaSeries_11 = import11.StackingAreaSeries;
    this._BarSeries_12 = import12.BarSeries;
    this._StackingBarSeries_13 = import13.StackingBarSeries;
    this._Tooltip_14 = import14.Tooltip;
    this._Crosshair_15 = import15.Crosshair;
    this._Category_16 = import16.Category;
    this._DateTime_17 = import17.DateTime;
    this._Logarithmic_18 = import18.Logarithmic;
    this._Marker_19 = import19.Marker;
    this._Legend_20 = import20.Legend;
    this._Zoom_21 = import21.Zoom;
    this._DataLabel_22 = import22.DataLabel;
    this._Selection_23 = import23.Selection;
    return this._ChartAllModule_2;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ChartModule)) { return this._ChartModule_1; }
    if ((token === import1.ChartAllModule)) { return this._ChartAllModule_2; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_3; }
    if ((token === import4.LineSeries)) { return this._LineSeries_4; }
    if ((token === import5.ScatterSeries)) { return this._ScatterSeries_5; }
    if ((token === import6.ColumnSeries)) { return this._ColumnSeries_6; }
    if ((token === import7.SplineSeries)) { return this._SplineSeries_7; }
    if ((token === import8.AreaSeries)) { return this._AreaSeries_8; }
    if ((token === import9.StepLineSeries)) { return this._StepLineSeries_9; }
    if ((token === import10.StackingColumnSeries)) { return this._StackingColumnSeries_10; }
    if ((token === import11.StackingAreaSeries)) { return this._StackingAreaSeries_11; }
    if ((token === import12.BarSeries)) { return this._BarSeries_12; }
    if ((token === import13.StackingBarSeries)) { return this._StackingBarSeries_13; }
    if ((token === import14.Tooltip)) { return this._Tooltip_14; }
    if ((token === import15.Crosshair)) { return this._Crosshair_15; }
    if ((token === import16.Category)) { return this._Category_16; }
    if ((token === import17.DateTime)) { return this._DateTime_17; }
    if ((token === import18.Logarithmic)) { return this._Logarithmic_18; }
    if ((token === import19.Marker)) { return this._Marker_19; }
    if ((token === import20.Legend)) { return this._Legend_20; }
    if ((token === import21.Zoom)) { return this._Zoom_21; }
    if ((token === import22.DataLabel)) { return this._DataLabel_22; }
    if ((token === import23.Selection)) { return this._Selection_23; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const ChartAllModuleNgFactory:import0.NgModuleFactory<import1.ChartAllModule> = new import0.NgModuleFactory<any>(ChartAllModuleInjector,import1.ChartAllModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvZWoyLWNoYXJ0LWNvbXBvbmVudHNfbWFzdGVyLVZTMk1UTUEzQU9FUUxJRUdJWUNUM1BVQlpFRENKRk9RSDNVVlZWRVhPV0dUSFVNR0E1TEEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2hhcnQvY2hhcnQtYWxsLm1vZHVsZS5uZ2ZhY3RvcnkudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9DOi9KZW5raW5zL3dvcmtzcGFjZS9lajItY2hhcnQtY29tcG9uZW50c19tYXN0ZXItVlMyTVRNQTNBT0VRTElFR0lZQ1QzUFVCWkVEQ0pGT1FIM1VWVlZFWE9XR1RIVU1HQTVMQS90aGlyZC1wYXJ0eS9hbmd1bGFyL3NyYy9jaGFydC9jaGFydC1hbGwubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7In0=
