/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../src/chart/chart.component';
import * as import2 from '@syncfusion/ej2-charts/src/chart/series/line-series';
import * as import3 from '@syncfusion/ej2-charts/src/chart/series/scatter-series';
import * as import4 from '@syncfusion/ej2-charts/src/chart/series/column-series';
import * as import5 from '@syncfusion/ej2-charts/src/chart/series/spline-series';
import * as import6 from '@syncfusion/ej2-charts/src/chart/series/area-series';
import * as import7 from '@syncfusion/ej2-charts/src/chart/series/step-line-series';
import * as import8 from '@syncfusion/ej2-charts/src/chart/series/stacking-column-series';
import * as import9 from '@syncfusion/ej2-charts/src/chart/series/stacking-area-series';
import * as import10 from '@syncfusion/ej2-charts/src/chart/series/bar-series';
import * as import11 from '@syncfusion/ej2-charts/src/chart/series/stacking-bar-series';
import * as import12 from '@syncfusion/ej2-charts/src/chart/user-interaction/tooltip';
import * as import13 from '@syncfusion/ej2-charts/src/chart/user-interaction/crosshair';
import * as import14 from '@syncfusion/ej2-charts/src/chart/axis/category-axis';
import * as import15 from '@syncfusion/ej2-charts/src/chart/axis/date-time-axis';
import * as import16 from '@syncfusion/ej2-charts/src/chart/axis/logarithmic-axis';
import * as import17 from '@syncfusion/ej2-charts/src/chart/series/marker';
import * as import18 from '@syncfusion/ej2-charts/src/chart/legend/legend';
import * as import19 from '@syncfusion/ej2-charts/src/chart/user-interaction/zooming';
import * as import20 from '@syncfusion/ej2-charts/src/chart/series/data-label';
import * as import21 from '@syncfusion/ej2-charts/src/chart/user-interaction/selection';
const styles_ChartComponent:any[] = ([] as any[]);
export const RenderType_ChartComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_ChartComponent,
  data: {}
}
);
export function View_ChartComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(2,([] as any[]),(null as any),(null as any));
}
function View_ChartComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),5,'ej-chart',([] as any[]),(null as any),(null as any),(null as any),View_ChartComponent_0,RenderType_ChartComponent)),
    import0.ɵdid(3268608,(null as any),4,import1.ChartComponent,[
      import0.ElementRef,
      [
        2,
        import2.LineSeries
      ]
      ,
      [
        2,
        import3.ScatterSeries
      ]
      ,
      [
        2,
        import4.ColumnSeries
      ]
      ,
      [
        2,
        import5.SplineSeries
      ]
      ,
      [
        2,
        import6.AreaSeries
      ]
      ,
      [
        2,
        import7.StepLineSeries
      ]
      ,
      [
        2,
        import8.StackingColumnSeries
      ]
      ,
      [
        2,
        import9.StackingAreaSeries
      ]
      ,
      [
        2,
        import10.BarSeries
      ]
      ,
      [
        2,
        import11.StackingBarSeries
      ]
      ,
      [
        2,
        import12.Tooltip
      ]
      ,
      [
        2,
        import13.Crosshair
      ]
      ,
      [
        2,
        import14.Category
      ]
      ,
      [
        2,
        import15.DateTime
      ]
      ,
      [
        2,
        import16.Logarithmic
      ]
      ,
      [
        2,
        import17.Marker
      ]
      ,
      [
        2,
        import18.Legend
      ]
      ,
      [
        2,
        import19.Zoom
      ]
      ,
      [
        2,
        import20.DataLabel
      ]
      ,
      [
        2,
        import21.Selection
      ]

    ]
    ,(null as any),(null as any)),
    import0.ɵqud(167772160,1,{childSeries: 0}),
    import0.ɵqud(167772160,2,{childAxes: 0}),
    import0.ɵqud(167772160,3,{childRows: 0}),
    import0.ɵqud(167772160,4,{childColumns: 0})
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const ChartComponentNgFactory:import0.ComponentFactory<import1.ChartComponent> = import0.ɵccf('ej-chart',import1.ChartComponent,View_ChartComponent_Host_0,{
  axes: 'axes',
  background: 'background',
  border: 'border',
  chartArea: 'chartArea',
  columns: 'columns',
  crosshair: 'crosshair',
  description: 'description',
  enablePersistence: 'enablePersistence',
  enableRtl: 'enableRtl',
  height: 'height',
  isMultiSelect: 'isMultiSelect',
  legendSettings: 'legendSettings',
  locale: 'locale',
  margin: 'margin',
  palettes: 'palettes',
  primaryXAxis: 'primaryXAxis',
  primaryYAxis: 'primaryYAxis',
  rows: 'rows',
  selectedDataIndexes: 'selectedDataIndexes',
  selectionMode: 'selectionMode',
  series: 'series',
  tabIndex: 'tabIndex',
  theme: 'theme',
  title: 'title',
  titleStyle: 'titleStyle',
  tooltip: 'tooltip',
  useGroupingSeparator: 'useGroupingSeparator',
  width: 'width',
  zoomSettings: 'zoomSettings'
}
,{
  animationComplete: 'animationComplete',
  axisLabelRender: 'axisLabelRender',
  chartMouseClick: 'chartMouseClick',
  chartMouseDown: 'chartMouseDown',
  chartMouseLeave: 'chartMouseLeave',
  chartMouseMove: 'chartMouseMove',
  chartMouseUp: 'chartMouseUp',
  dragComplete: 'dragComplete',
  legendRender: 'legendRender',
  load: 'load',
  loaded: 'loaded',
  pointRender: 'pointRender',
  seriesRender: 'seriesRender',
  textRender: 'textRender',
  tooltipRender: 'tooltipRender',
  zoomComplete: 'zoomComplete'
}
,([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiQzovSmVua2lucy93b3Jrc3BhY2UvZWoyLWNoYXJ0LWNvbXBvbmVudHNfbWFzdGVyLVZTMk1UTUEzQU9FUUxJRUdJWUNUM1BVQlpFRENKRk9RSDNVVlZWRVhPV0dUSFVNR0E1TEEvdGhpcmQtcGFydHkvYW5ndWxhci9zcmMvY2hhcnQvY2hhcnQuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlL2VqMi1jaGFydC1jb21wb25lbnRzX21hc3Rlci1WUzJNVE1BM0FPRVFMSUVHSVlDVDNQVUJaRURDSkZPUUgzVVZWVkVYT1dHVEhVTUdBNUxBL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NoYXJ0L2NoYXJ0LmNvbXBvbmVudC50cyIsIm5nOi8vL0M6L0plbmtpbnMvd29ya3NwYWNlL2VqMi1jaGFydC1jb21wb25lbnRzX21hc3Rlci1WUzJNVE1BM0FPRVFMSUVHSVlDVDNQVUJaRURDSkZPUUgzVVZWVkVYT1dHVEhVTUdBNUxBL3RoaXJkLXBhcnR5L2FuZ3VsYXIvc3JjL2NoYXJ0L2NoYXJ0LmNvbXBvbmVudC50cy5DaGFydENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxlai1jaGFydD48L2VqLWNoYXJ0PiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO2dCQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7TUFBQTtRQUFBOztNQUFBOztNQUFBO1FBQUE7O01BQUE7O01BQUE7UUFBQTs7TUFBQTs7SUFBQTtLQUFBO2dCQUFBO2dCQUFBO2dCQUFBO2dCQUFBOzs7SUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
